# Maths Basics

## Vectors

In [3]:
## getting vectors

x = [1, 2, 3, 4, 5]
x

[1, 2, 3, 4, 5]

In [7]:
# importing numpy

import numpy as np
x = np.array([1, 2, 3, 4, 5])

print(x)

[1 2 3 4 5]


## Matrices

In [10]:
## getting matrices

m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])

# view matrix
print(m)

# view dimensions
print(m.shape)

[[1 5 2]
 [4 7 4]
 [2 0 9]]
(3, 3)


## Matrix Transpose

In [11]:
# matrix transpose

print('Matrix Transpose:\n', m.transpose(), '\n')

Matrix Transpose:
 [[1 4 2]
 [5 7 0]
 [2 4 9]] 



## Matrix Determinant

In [12]:
# matrix determinant

print ('Matrix Determinant:', np.linalg.det(m), '\n')

Matrix Determinant: -105.00000000000006 



## Matrix Inverse

In [13]:
# matrix inverse

m_inv = np.linalg.inv(m)
print ('Matrix inverse:\n', m_inv, '\n')

Matrix inverse:
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 



## Identity Matrix

In [15]:
# identity matrix 

iden_m =  np.dot(m, m_inv)
iden_m = np.round(np.abs(iden_m), 0)
print ('Product of matrix and its inverse:\n', iden_m)

Product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Descriptive Statistics

In [14]:
# descriptive statistics
import scipy as stats
import numpy as np
from scipy.stats import distributions

# get data
nums = np.random.randint(1,20, size=(1,15))[0]
print('Data: ', nums)


Data:  [ 3 19  3 11 17  4 11  2  7 17  2  5  5  2 13]


In [15]:
# get descriptive stats
print ('Mean:', sp.mean(nums))
print ('Median:', sp.median(nums))
print ('Mode:', sp.stats.mode(nums))
print ('Standard Deviation:', sp.std(nums))
print ('Variance:', sp.var(nums))
print ('Skew:', sp.stats.skew(nums))
print ('Kurtosis:', sp.stats.kurtosis(nums))

Mean: 8.066666666666666
Median: 5.0
Mode: ModeResult(mode=array([2]), count=array([3]))
Standard Deviation: 5.88179866669674
Variance: 34.59555555555555
Skew: 0.6051935447232574
Kurtosis: -1.1283924042677462
